### ISSUE TITLE
Placeholder doesn't work

### ISSUE THREAD

**Issue by HamzaInPerth** [sagalbot/vue-select#1355]
Placeholder doesn't work, so I updated my version, but still does'nt work.

My component is blank but still have options and the function got executed as well.

I'm using firefox dev version

Here's a piece of my code :

```
        <v-select
          id="department"
          label="department"
          class="shadow-sm"
          :options="$store.getters['localData/getDepartment']"
          :reduce="(value) => value.id"
          @input="sortEmployeesByDepartment"
          v-model="id_department"
          placeholder="Here is my placeholder">
        </v-select>
```

**Comment by HamzaInPerth** [comment]
The issue is due to width in CSS, you have to define a width. Hope it will help someone.

**Comment by rommyarb** [comment]
You need to define `width` in the style.
```vue
<v-select
  style="width:250px"
  id="department"
  label="department"
  class="shadow-sm"
  :options="$store.getters['localData/getDepartment']"
  :reduce="(value) => value.id"
  @input="sortEmployeesByDepartment"
  v-model="id_department"
  placeholder="Here is my placeholder">
</v-select>
```

**Comment by ashraful19** [comment]
Though the issue is old, but i wanted to share the exact reason i just found out. 
Seems like when `searchable` is `false`, the placeholder doesnt show because the searching input has `flex: none !important`.
To overcome this, the corrent solution is to add this into your css,
```
.vs--unsearchable .vs__dropdown-toggle .vs__selected-options .vs__search {
    flex: auto !important;
}
```
and this solved the issue properly. setting the `width` leads to other ui issues.
