### ISSUE TITLE
Invalid prop: type check failed for prop "options". Expected Array, got Object.

### ISSUE THREAD

**Issue by shern91** [sagalbot/vue-select#393]
I'm using VueJS 2 and Asp.net core 1.1 to develop my project. I make a vue select for search user via id, due to only search by id, it will only return single object for each time search. When I key in user id in that select field, I get this error 'Invalid prop: type check failed for prop "options". Expected Array, got Object.'

If i use

`results: null` instead of `results: []` (this is v-model bind to options)

I will get another error ' Error in created hook: "TypeError: Cannot read property 'slice' of null"', how could i assign my results data to object or null to let my options can received object?

Another error is when on-search event is trigger, i use axios to fetch result from database, I assign the response.data to results array then console log the results array, it does store the value, but my options list does not updated.

Thanks in advance!

**Comment by MarZab** [comment]
related to https://github.com/sagalbot/vue-select/issues/393

**Comment by IParthJoshi** [comment]
For your first question, here is what i understand and giving solution on base of that.

<v-select :options="array" v-model="selected"></v-select>
data(){ 
return {
array:[],
selected: null
}
}

This should work perfectly fine.
And so your options list will be updated as it should.

**Comment by navstev0** [comment]
I came here this the same error, but the cause if not well described.

According to #1032 the correct way to assign default properties is, to use a function like `() => []`.
However this is the cause the error, so at the moment the three options described as use cases will cause one of three errors, and arrays cannot be defaulted without warning or error.

```
props : {
  aryTest: {
    type : Array,
    default : () => []
  }
}
```
[Vue warn]: Invalid prop: type check failed for prop "aryTest". Expected Array, got Object.

```
props : {
  aryTest: {
    type : Array,
    default : []
  }
}
```
[Vue warn]: Invalid default value for prop "aryTest": Props with type Object/Array must use a factory function to return the default value.

```
props : {
  aryTest: {
    type : Array
  }
},
data(){ 
  return {
    aryTest : []
  };
}
```
[Vue warn]: The data property "aryTest" is already declared as a prop. Use prop default value instead.

```
props : {
  aryTest: {
    type : Array
  }
},
created(){
  this.aryTest = this.aryTest || [];
}
```
[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "aryTest"

Aside from a null check inside the component there is little else I can think of to get around this.

**Comment by navstev0** [comment]
Sorry that comment belongs on the vue issues board, thought that's where I was from the google search.

**Comment by eraporsmk** [comment]
I experienced the same thing
the error that i found was
```
[Vue warn]: Invalid prop: type check failed for prop "options". Expected Array, got String with value "".
```
my code
```
data() {
        return {
            form: new Form({
                komponen: [],
            })
        }
    }
```
in html 
```
<v-select :options="form.komponen" label="text" index="value" @input="getAspek" v-model="form.komponen_id" placeholder="== Pilih Komponen == "></v-select>
```
When I first opened the page, there was no error
but when I submit the form using ```this.form.post()``` then the error appears

sorry for bad english

**Comment by sardar1592** [comment]
It seems like a lifecycle issue. In my case swapping with Vuex did the trick.
